version: '3'
services:
  server:
    build: ./docker/server
    container_name: 'webpagetest_server'
    ports:
     - '4000:80'

  agent:
    build: ./docker/agent
    container_name: 'webpagetest_agent'
    network_mode: "host"
    shm_size: '1gb'
    environment:
      - SERVER_URL=http://localhost:4000/work/
      - LOCATION=Test
